"""followers

Revision ID: 12984d80967a
Revises: f4aad984e0c4
Create Date: 2018-06-26 08:28:57.682172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12984d80967a'
down_revision = 'f4aad984e0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
